Added new defintions
lhcb/glossary pull request #53
Opened 2021-11-02 13:51 UTC by vlukashenko

Adding definitions of BPV, CLARO, Delphes, GBTx, HPD, MaPMT, MiniDAQ, ODIN, PCIe40, Readout board, sODIN, SOL40, sWeights, TELL40, TFC, Timepix, Tracker-only, VeloPix

Crediting also Robbert Geertsema for a great review of the Timepix and Velopix definitions. 

I am not really sure but some github ci test for creating a github book fails because I don't have some token...

2021-11-02 13:56 UTC, eduardo-rodrigues commented
Thanks for this! So I guess that we should tick off some bits at least in https://github.com/lhcb/glossary/issues/34, potentially in other open issues (to be checked)?

2021-11-02 13:58 UTC, vlukashenko commented
> Thanks for this! So I guess that we should tick off some bits at least in #34, potentially in other open issues (to be checked)?

No problem! Will tick off :)

2021-11-02 14:19 UTC, eduardo-rodrigues commented on glossary/C.md
> +CLARO is a cusotmized 8 channle ASIC CMOS chip used to read-out RICH MaPMTs in Upgrade 1.
I see at least 3 typos in this definition of 3-ish sentences :S. Can you "review yourself" for trivialities before somebody goes more into detail concerning the definitions and explanations themselves? Seems more effective IMO. Advance thanks.

2021-11-02 15:03 UTC, vlukashenko commented on glossary/C.md
> +CLARO is a cusotmized 8 channle ASIC CMOS chip used to read-out RICH MaPMTs in Upgrade 1.
Yeah, that was a particularly bad case... Sorry for that 😓 I just run the definitions through the languagetool for the stupid grammar mistakes. Keep in mind that I am coming from a language where no articles are used, so I can still mess up with a/the usage, but I tried my best to fix it.

2021-11-02 15:04 UTC, eduardo-rodrigues commented on glossary/T.md
> +A fast simulation that excludes calorimeter and muon geometry, but keeps the RICH geometry included. However, RICH physics lists are switched off.
```suggestion
A fast simulation configuration that excludes «calorimeter:CALO» and «MUON» geometry, but keeps the «RICH» geometry included. However, RICH physics lists are switched off.    
```

2021-11-02 15:05 UTC, eduardo-rodrigues commented on glossary/T.md
> +A fast simulation that excludes calorimeter and muon geometry, but keeps the RICH geometry included. However, RICH physics lists are switched off.
@vlukashenko, as you can see these ``«calorimeter:CALO» and «MUON»` are the two ways in which we define cross-links, but it seems you did not follow this convention, no idea why. It's a bit painful but can you adapt as in my example above?

2021-11-02 15:06 UTC, eduardo-rodrigues commented on glossary/C.md
> +CLARO is a cusotmized 8 channle ASIC CMOS chip used to read-out RICH MaPMTs in Upgrade 1.
Understood :-). As said, my suggested seemed more effective / appropriate. No big deal.

2021-11-02 15:08 UTC, eduardo-rodrigues commented on glossary/H.md
> +A vacuum photodetector, that consists of a vacuum photon tube and a pixel silicon detector.
```suggestion
A vacuum photodetector consisting of a vacuum photon tube and a pixel silicon detector.
```

2021-11-02 15:08 UTC, eduardo-rodrigues commented on glossary/H.md
> +HPDs were used in the original LHCb design (Run 1 and Run 2).
```suggestion
HPDs were used in the original LHCb design (Runs 1 and 2).
```

2021-11-02 15:44 UTC, eduardo-rodrigues requested changes
I made a few changes in the hope to fix the build failure. Please accept and fingers crossed. Then we can proceed with the actual review.

2021-11-02 16:19 UTC, eduardo-rodrigues commented on glossary/A.md
> +Application specific integrated circuit.
```suggestion
See the [Wikipedia definition](https://en.wikipedia.org/wiki/Application-specific_integrated_circuit).
```

2021-11-02 16:19 UTC, eduardo-rodrigues commented on glossary/A.md
> +## ASIC: application specific integrated circuit {#ASIC}
```suggestion
## ASIC: application-specific integrated circuit {#ASIC}
```

2021-11-02 16:21 UTC, eduardo-rodrigues commented on glossary/C.md
> +CLARO is a customized 8 channel ASIC CMOS chip used to read-out «RICH» «MaPMT»s in Upgrade 1.
```suggestion
CLARO is a customized 8 channel «ASIC» CMOS chip used to read-out «RICH» «MaPMT»s in Upgrade 1. 
```

2021-11-02 16:45 UTC, eduardo-rodrigues commented on glossary/T.md
> +An «application specific integrated circuit:ASIC»(ASIC) used in hybrid pixel detectors and has 256x256 pixels of 55$$\mu$$m pitch.
```suggestion
An «application specific integrated circuit:ASIC» (ASIC) used in hybrid pixel detectors and has 256x256 pixels of 55$$\mu$$m pitch.
```

2021-11-02 16:45 UTC, vlukashenko commented on glossary/B.md
> +Online: a «primary vertex:PV» that a track has the smallest «impact parameter:IP» with.
I think because instead of merging your suggestions first I have locally fixed some stuff that I found myself in parallel, so it overwrote the suggestion. Will fix it

2021-11-02 16:59 UTC, eduardo-rodrigues approved these changes
Let me make a tmp approval to re-run the CI and the building of the book.

2021-11-02 17:03 UTC, eduardo-rodrigues commented
The CI failure is strange. I'm going to make a simple MR only adding the definition of ASIC to check if the problem really is somewhere in the changes of the MR or it's a more general one ...

2021-11-02 17:07 UTC, eduardo-rodrigues commented on glossary/B.md
> +Offline: a primary vertex with respect to which a particle (or a track) has the smallest $$IP\chi^{2}$$.
```suggestion
Offline: a primary vertex with respect to which a particle (or a track) has the smallest IP $$\chi^{2}$$. 
```

2021-11-02 17:08 UTC, eduardo-rodrigues commented on glossary/C.md
> +It is a digital board with a binary output: either 0 or 1.
```suggestion
It is a digital board with a binary output. 
```

2021-11-02 17:09 UTC, eduardo-rodrigues commented on glossary/M.md
> +They replace the previous photodetectors, called [HPD](#HPD).
```suggestion
They replace the previous photodetectors, called «HPD».
```

2021-11-02 17:10 UTC, eduardo-rodrigues commented on glossary/M.md
> +A readout system development stage server that hosts «timing and fast control system:TFC» and «data acquisition:DAQ» systems, see [LHCb MiniDAQ control system](https://cds.cern.ch/record/2702137/file
```suggestion
A readout system development stage server that hosts «timing and fast control system:TFC» and «data acquisition:DAQ» systems, see the [MiniDAQ control system](https://cds.cern.ch/record/2702137/files/10.1051_epjconf_201921401005.pdf) document.
```

2021-11-02 17:11 UTC, eduardo-rodrigues commented on glossary/O.md
> +A readout supervision module of «timing and fact control:TFC», see [The final LHCb readout supervisor ODIN](https://cds.cern.ch/record/619217/files/p371.pdf) for LHCb Run 1/Run 2 version.
```suggestion
A readout supervision module of «timing and fact control:TFC», see the final [Readout Supervisor ODIN](https://cds.cern.ch/record/619217/files/p371.pdf) document for Runs 1 and Run 2.
```

2021-11-02 17:11 UTC, eduardo-rodrigues commented on glossary/O.md
> +An updated version used in Upgrade 1 is called «S-ODIN:S_ODIN».
```suggestion
An updated version used in Upgrade I is called «S-ODIN:S_ODIN».
```

2021-11-02 17:11 UTC, vlukashenko commented
> The CI failure is strange. I'm going to make a simple MR only adding the definition of ASIC to check if the problem really is somewhere in the changes of the MR or it's a more general one ...

Probably that last HPD link was an issue.

2021-11-02 17:12 UTC, eduardo-rodrigues commented on glossary/P.md
> +«Readout boards:ReadoutBoard» used for the «data acquisition system:DAQ», «Experiment control system:ECS» and «timing and fast control:TFC», see [LHCb Trigger and Online TDR](https://cds.cern.ch/reco
```suggestion
«Readout boards:ReadoutBoard» used for the «data acquisition system:DAQ», «Experiment Control System:ECS» and «Timing and Fast Control:TFC». Refer to the [LHCb Trigger and Online TDR](https://cds.cern.ch/record/1701361/files/LHCB-TDR-016.pdf) for details.
```

2021-11-02 17:13 UTC, eduardo-rodrigues commented on glossary/P.md
> +Each board has 48 bidirectional optical links for interfacing with frontend electronics and one bidirectional optical link for interfacing the TFC.
```suggestion
Each board has 48 bidirectional optical links for interfacing with frontend electronics and one bidirectional optical link for interfacing the «TDC».
```

2021-11-02 17:14 UTC, eduardo-rodrigues commented on glossary/R.md
> +In LHCb PCI Express 40 board is used, see [LHCb Trigger and Online TDR](https://cds.cern.ch/record/1701361/files/LHCB-TDR-016.pdf) and «PCIe40».
Can you improve this sentence? Not sure what you mean.

2021-11-02 17:15 UTC, eduardo-rodrigues commented
> > The CI failure is strange. I'm going to make a simple MR only adding the definition of ASIC to check if the problem really is somewhere in the changes of the MR or it's a more general one ...
> 
> Probably that last HPD link was an issue.

I suspect so. Found it after I made that MR # 54 and started reviewing from top to bottom.

2021-11-02 17:39 UTC, eduardo-rodrigues commented on glossary/B.md
> +## BPV: Best Primary Vertex {#BPV}
Not that I believe this should matter but BPV should come after Bookkeeping and Boole.

2021-11-02 17:43 UTC, eduardo-rodrigues commented on glossary/C.md
> +CLARO is a customized 8-channel «ASIC» CMOS chip used to read out «RICH» «MaPMT»s in Upgrade I.
```suggestion
CLARO is a customized 8-channel «ASIC» CMOS chip used to read out «RICH» «MaPMT»s in Upgrade I.
```

2021-11-02 17:43 UTC, eduardo-rodrigues commented on glossary/C.md
> +It is a digital board with a binary output.
```suggestion
It is a digital board with a binary output.
```

2021-11-02 17:47 UTC, eduardo-rodrigues commented on glossary/G.md
> +
```suggestion
```

2021-11-02 17:59 UTC, eduardo-rodrigues commented on glossary/S.md
> +A «timing and fast control: TFC» readout supervision module responsible for generating necessary information and commands, see [LHCb Trigger and Online TDR](https://cds.cern.ch/record/1701361/files/L
```suggestion
A «timing and fast control: TFC» readout supervision module responsible for generating necessary information and commands, see [LHCb Trigger and Online TDR](https://cds.cern.ch/record/1701361/files/LHCB-TDR-016.pdf) and «ODIN».
```

2021-11-02 18:06 UTC, eduardo-rodrigues commented on glossary/P.md
> +Each board has 48 bidirectional optical links for interfacing with frontend electronics and one bidirectional optical link for interfacing the «TDC».
TDC should be TFC, right ;-)?

2021-11-02 18:08 UTC, eduardo-rodrigues commented on glossary/D.md
> +Data Acquisition system.
```suggestion
Acronym for Data Acquisition system. See the [Wikipedia introduction](https://en.wikipedia.org/wiki/Data_acquisition).
```

2021-11-02 18:08 UTC, eduardo-rodrigues commented on glossary/D.md
> +See more [here](https://www.epj-conferences.org/articles/epjconf/pdf/2019/19/epjconf_chep2018_02024.pdf).
```suggestion
See more in these [CHEP 2018 proceedings](https://www.epj-conferences.org/articles/epjconf/pdf/2019/19/epjconf_chep2018_02024.pdf).
```

2021-11-02 18:08 UTC, eduardo-rodrigues commented on glossary/G.md
> +A serializer-de-serializer chip receiving and transmitting serial data at 4.8 Gb/s, that uses GBT protocol.
```suggestion
A serializer-de-serializer chip receiving and transmitting serial data at 4.8 Gb/s, which uses GBT protocol.
```

2021-11-02 18:09 UTC, eduardo-rodrigues commented on glossary/G.md
> +See [The GBT project](https://cds.cern.ch/record/1235836/files/p342).
```suggestion
See the [GBT project](https://cds.cern.ch/record/1235836/files/p342) document.
```

2021-11-02 18:09 UTC, eduardo-rodrigues commented on glossary/M.md
> +MaPMTs were installed with Upgrade-1 in RICH 1 and RICH 2.
```suggestion
MaPMTs were installed in RICH 1 and RICH 2 for Upgrade I.
```

2021-11-02 18:10 UTC, eduardo-rodrigues commented on glossary/M.md
> +RICH 1 and inner parts of RICH 2 are covered by the 25.4 x 25.4 mm MaPMTs with 64 channels.
```suggestion
RICH 1 and the inner parts of RICH 2 are covered by the 25.4 x 25.4 mm MaPMTs with 64 channels.
```

2021-11-02 18:10 UTC, eduardo-rodrigues commented on glossary/M.md
> +Outer area of RICH 2 is covered with 50.8 x 50.8 mm MaPMTs with 64 channels.
```suggestion
The outer area of RICH 2 is covered with 50.8 x 50.8 mm MaPMTs with 64 channels.
```

2021-11-02 18:11 UTC, eduardo-rodrigues commented on glossary/P.md
> +Each board has 48 bidirectional optical links for interfacing with frontend electronics and one bidirectional optical link for interfacing the «TDC».
```suggestion
Each board has 48 bidirectional optical links for interfacing with the frontend electronics and one bidirectional optical link for interfacing with the «TFC».
```

2021-11-02 18:35 UTC, eduardo-rodrigues commented on glossary/T.md
> +## Tracker-only {#TrackerOnly}
```suggestion
```

2021-11-02 18:35 UTC, eduardo-rodrigues commented on glossary/T.md
> +
```suggestion
```

2021-11-02 18:35 UTC, eduardo-rodrigues commented on glossary/T.md
> +A fast simulation configuration that excludes «calorimeter:CALO» and «MUON» geometry, but keeps the «RICH» geometry included. However, RICH physics lists are switched off.
```suggestion
```

2021-11-02 18:36 UTC, eduardo-rodrigues commented on glossary/T.md
> +
```suggestion
```

2021-11-02 18:36 UTC, eduardo-rodrigues commented on glossary/T.md
> +A fast simulation configuration that excludes «calorimeter:CALO» and «MUON» geometries, but keeps the «RICH» geometry included. However, RICH physics lists are switched off.
```suggestion
A fast simulation configuration that excludes «calorimeter:CALO» and «MUON» geometries but keeps the «RICH» geometry included. However, RICH physics lists are switched off.
```

2021-11-03 10:09 UTC, eduardo-rodrigues commented
Superseeded by https://github.com/lhcb/glossary/pull/54.

2021-11-03 10:09 UTC, closed without merging